### ISSUE TITLE
Remove custom CSS that effects globally

### ISSUE THREAD

**Issue by jayasanka-sack** [acf-sack/sack-site#340]
**Is your feature request related to a problem? Please describe.**
There are some custom CSS classes that affect the whole elements such as headings, paragraphs. 
Please remove them from the custom.css file. 

ex: 

```css
 body h3, body h4, body h5 {
  font-family: Lato, sans-serif;
  color: #2e8df3;
  font-weight: 700;
}
```

This is wrong. We should not select elements unless there's a specific reason. 

**Are you working on it?**
No
